# Generated by Django 4.2.6 on 2023-11-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
    ]
